// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izsgeunpgfsyrdikxaob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6c2dldW5wZ2ZzeXJkaWt4YW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzk4NzksImV4cCI6MjA2OTk1NTg3OX0.j3JCzQW7KTw92xPWiddM1p0t1q5zR6txyapOU8Il8j8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});